restapi: xkcd parsing implementation, #3
gumalevskij/golang pull request #4
Opened 2024-04-03 05:00 UTC by gumalevskij

#3 
[vbelogrudov](https://github.com/vbelogrudov), please, review

2024-04-03 19:21 UTC, vbelogrudov requested changes
еще лучше добавить сюда промежуточное сохранение в database.json накопленных данных и чтение из database.json при старте, чтобы не бегать долго в xkcd.com каждый запуск, а только если в xkcd.com появились новые комиксы

2024-04-03 19:21 UTC, vbelogrudov commented on RESTAPI/cmd/xkcd/main.go
> +	config, err := xkcd.LoadConfig("config.yaml")
я бы добавил еще один флаг, -c для конфига, если запускаемся не с текущей директории

2024-04-03 19:21 UTC, vbelogrudov commented on RESTAPI/pkg/xkcd/xkcd.go
> +func LoadConfig(path string) (*database.Config, error) {
по-хорошему, мы ничего не хотим знать о database пакете

2024-04-03 19:21 UTC, vbelogrudov commented on RESTAPI/pkg/xkcd/xkcd.go
> +	Transcript string
помимо транскрипта в комиксах есть alt - его тоже желательно добывать

2024-04-03 19:21 UTC, vbelogrudov commented on RESTAPI/pkg/database/database.go
> +func LoadConfig(path string) (*Config, error) {
это лучше убрать поближе к  main()

2024-04-03 19:21 UTC, vbelogrudov commented on RESTAPI/pkg/database/database.go
> +	return ioutil.WriteFile(path, data, 0644)
os.WriteFile. Старая функция - deprecated

2024-04-03 19:21 UTC, vbelogrudov commented on RESTAPI/cmd/xkcd/main.go
> +		normComics[fmt.Sprint(comic.Num)] = map[string]interface{}{
лучше strconv.Itoa, fmt функции достаточно тяжелые

2024-04-03 19:21 UTC, vbelogrudov commented on RESTAPI/cmd/xkcd/main.go
> +	normComics := make(map[string]interface{})
лучше не использовать интерфейсы для известных типов/структур. Например, можно завести в database свой type Comics и создавать map[string]database.Comics

2024-04-03 19:23 UTC, vbelogrudov commented
не хватает автоматического определения конечного id комикса:

RESTAPI$ ./xkcd -n 10000
2024/04/03 22:20:08 Failed to fetch comics: invalid character '<' looking for beginning of value

2024-04-07 05:35 UTC, gumalevskij commented
Спасибо за замечания, [vbelogrudov](https://github.com/vbelogrudov)! Всё поправил, посмотри, пожалуйста, повторно

2024-04-07 13:28 UTC, vbelogrudov approved these changes
получилось хорошо, кратко и понятно!

2024-04-07 13:28 UTC, vbelogrudov commented on RESTAPI/cmd/xkcd/main.go
> +	data, err := ioutil.ReadFile(path)
мелочь, ioutil.ReadFile - deprecated, лучше использовать os.ReadFile()

2024-04-07 13:28 UTC, vbelogrudov commented on RESTAPI/cmd/xkcd/main.go
> +func NormalizeComics(stopWordsFile string, comics []xkcd.Comic, normComics *database.Comics) error {
мелочь - map у нас как тип всегда указатель сам по себе, не нужно его передавать со звездой. А еще лучше просто отдавать через return

2024-04-07 13:28 UTC, vbelogrudov commented on RESTAPI/pkg/xkcd/xkcd.go
>  	var comics []Comic
здесь мы можем сразу определить оптимальный размер с make(), чтобы не расти 1, 2, 4, 8, 16 ...

2024-04-07 13:29 UTC, vbelogrudov commented
еще бы в будущем сообщение о прогрессе, например, какой-нибудь принт через каждые 100 комиксов

2024-04-08 14:26 UTC, gumalevskij commented on RESTAPI/cmd/xkcd/main.go
> +	data, err := ioutil.ReadFile(path)
Поставил, go расширение в vscode, теперь такое всегда буду замечать:)

2024-04-08 14:47 UTC, merged